
name: Generate Static Pages

on:
  push:
    branches: [ main ]
  schedule:
    # Запуск каждый день в 3:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Возможность запуска вручную

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate static pages
      run: npm run generate
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/
        git diff --staged --quiet || (git commit -m "Автообновление статических страниц [skip ci]" && git push)
